"use client";

import { ChevronRight, Search, UsersRound } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import {
	Empty,
	EmptyDescription,
	EmptyHeader,
	EmptyMedia,
	EmptyTitle,
} from "@/components/ui/empty";
import {
	InputGroup,
	InputGroupAddon,
	InputGroupInput,
} from "@/components/ui/input-group";
import {
	Table,
	TableBody,
	TableCell,
	TableHead,
	TableHeader,
	TableRow,
} from "@/components/ui/table";
import { Tooltip, TooltipTrigger } from "@/components/ui/tooltip";
import { useSharedViewRefresh } from "@/hooks/use-shared-view-refresh";
import { cn } from "@/lib/utils";
import type { TeamListItem } from "@/types";

interface TeamOverviewProps {
	teams: TeamListItem[];
}

// Derives a compact two-letter fallback from a team name.
function teamInitials(name: string) {
	return name
		.trim()
		.split(/\s+/)
		.slice(0, 2)
		.map((word) => word[0]?.toUpperCase())
		.join("");
}

// Renders searchable table rows for Teams generated by multi-member Projects.
export function TeamOverview({ teams }: TeamOverviewProps) {
	useSharedViewRefresh();
	const [search, setSearch] = useState("");
	const normalizedSearch = search.trim().toLowerCase();
	const visibleTeams = useMemo(
		() =>
			teams.filter(
				(team) =>
					!normalizedSearch ||
					`${team.name} ${team.description ?? ""}`
						.toLowerCase()
						.includes(normalizedSearch),
			),
		[normalizedSearch, teams],
	);

	return (
		<section className="flex min-h-[calc(100dvh-5rem)] flex-col">
			<header className="flex min-h-14 flex-col justify-center gap-3 border-b py-3 sm:flex-row sm:items-center sm:justify-between">
				<TooltipTrigger delay={400}>
					<h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
						Teams
					</h1>
					<Tooltip placement="bottom start">Back to dashboard</Tooltip>
				</TooltipTrigger>

				<InputGroup className="h-8.5 w-48 bg-card border-border shadow-2xs sm:w-56">
					<InputGroupAddon>
						<Search aria-hidden="true" className="text-muted-foreground" />
					</InputGroupAddon>
					<InputGroupInput
						id="team-search"
						value={search}
						onChange={(event) => setSearch(event.target.value)}
						placeholder="Search teams…"
						aria-label="Search teams"
					/>
				</InputGroup>
			</header>

			<div className="flex-1 py-5">
				{visibleTeams.length > 0 ? (
					<Table
						aria-label="Teams list"
						containerClassName="rounded-2xl border border-border shadow-xs"
					>
						<TableHeader>
							<TableHead isRowHeader className="px-5 py-3 text-xs">
								Team
							</TableHead>
							<TableHead className="px-5 py-3 text-xs w-32">
								Your Role
							</TableHead>
							<TableHead className="px-5 py-3 text-xs w-36">Members</TableHead>
							<TableHead className="w-24 px-5 py-3 text-right text-xs">
								Action
							</TableHead>
						</TableHeader>
						<TableBody>
							{visibleTeams.map((team) => (
								<TableRow key={team.id} id={team.id}>
									<TableCell className="px-5 py-3.5">
										<div className="flex min-w-56 items-center gap-3">
											<Avatar size="sm">
												<AvatarFallback className="bg-brand_navy-500/10 text-brand_navy-700 dark:bg-brand_mint-500/15 dark:text-brand_mint-300 text-[10px] font-semibold">
													{teamInitials(team.name)}
												</AvatarFallback>
											</Avatar>
											<div className="min-w-0">
												<Link
													href={`/team/${team.id}`}
													className="truncate font-semibold text-foreground text-sm hover:text-brand-primary transition-colors block"
												>
													{team.name}
												</Link>
												{team.description ? (
													<p className="truncate text-xs text-muted-foreground max-w-md">
														{team.description}
													</p>
												) : null}
											</div>
										</div>
									</TableCell>

									<TableCell className="px-5 py-3.5 align-middle">
										<Badge
											variant="secondary"
											className="h-5 px-2 text-[10px] font-medium border-border/50 capitalize"
										>
											{team.accessRole === "owner"
												? "Owner"
												: team.accessRole === "manager"
													? "Manager"
													: "Member"}
										</Badge>
									</TableCell>

									<TableCell className="px-5 py-3.5 align-middle">
										<span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground font-medium">
											<UsersRound
												className="size-3.5 text-brand_teal-600 dark:text-brand_mint-400"
												aria-hidden="true"
											/>
											{team.memberCount}{" "}
											{team.memberCount === 1 ? "member" : "members"}
										</span>
									</TableCell>

									<TableCell className="px-5 py-3.5 text-right align-middle">
										<Link
											href={`/team/${team.id}`}
											className={cn(
												buttonVariants({ variant: "ghost", size: "sm" }),
												"h-7 text-xs px-2.5 font-medium inline-flex items-center gap-1",
											)}
										>
											Open <ChevronRight className="size-3.5" />
										</Link>
									</TableCell>
								</TableRow>
							))}
						</TableBody>
					</Table>
				) : (
					<Empty className="h-full min-h-80 border-0">
						<EmptyHeader>
							<EmptyMedia variant="icon">
								<UsersRound />
							</EmptyMedia>
							<EmptyTitle>
								{search ? "No matching teams" : "No teams yet"}
							</EmptyTitle>
							<EmptyDescription>
								{search
									? "Try a different search term or clear the search."
									: "A team appears when a project gains a second member."}
							</EmptyDescription>
						</EmptyHeader>
					</Empty>
				)}
			</div>

			<footer className="flex items-center justify-between gap-4 border-t pt-3">
				<p className="text-xs text-muted-foreground">
					{visibleTeams.length} {visibleTeams.length === 1 ? "Team" : "Teams"}
				</p>
			</footer>
		</section>
	);
}
