"use client";

import { Search, UsersRound } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
	Empty,
	EmptyDescription,
	EmptyHeader,
	EmptyMedia,
	EmptyTitle,
} from "@/components/ui/empty";
import {
	InputGroup,
	InputGroupAddon,
	InputGroupInput,
} from "@/components/ui/input-group";
import { Tooltip, TooltipTrigger } from "@/components/ui/tooltip";
import { useSharedViewRefresh } from "@/hooks/use-shared-view-refresh";
import type { TeamListItem } from "@/types";

interface TeamOverviewProps {
	teams: TeamListItem[];
}

// Derives a compact two-letter fallback from a team name.
function teamInitials(name: string) {
	return name
		.trim()
		.split(/\s+/)
		.slice(0, 2)
		.map((word) => word[0]?.toUpperCase())
		.join("");
}

// Renders searchable cards for Teams generated by multi-member Projects.
export function TeamOverview({ teams }: TeamOverviewProps) {
	useSharedViewRefresh();
	const [search, setSearch] = useState("");
	const normalizedSearch = search.trim().toLowerCase();
	const visibleTeams = useMemo(
		() =>
			teams.filter(
				(team) =>
					!normalizedSearch ||
					`${team.name} ${team.description ?? ""}`
						.toLowerCase()
						.includes(normalizedSearch),
			),
		[normalizedSearch, teams],
	);

	return (
		<section className="flex min-h-[calc(100dvh-5rem)] flex-col">
			<header className="flex min-h-14 flex-col justify-center gap-3 border-b py-3 sm:flex-row sm:items-center sm:justify-between">
				<TooltipTrigger delay={400}>
					<h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
						Teams
					</h1>
					<Tooltip placement="bottom start">Back to dashboard</Tooltip>
				</TooltipTrigger>

				<InputGroup className="h-8.5 w-48 bg-card border-border shadow-2xs sm:w-56">
					<InputGroupAddon>
						<Search aria-hidden="true" className="text-muted-foreground" />
					</InputGroupAddon>
					<InputGroupInput
						value={search}
						onChange={(event) => setSearch(event.target.value)}
						placeholder="Search teams…"
						aria-label="Search teams"
					/>
				</InputGroup>
			</header>

			<div className="flex-1 py-5">
				{visibleTeams.length > 0 ? (
					<div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
						{visibleTeams.map((team) => (
							<div
								key={team.id}
								className="group relative rounded-2xl outline-none focus-within:ring-3 focus-within:ring-ring/40"
							>
								<Link
									href={`/team/${team.id}`}
									className="absolute inset-0 z-10 rounded-2xl"
								>
									<span className="sr-only">Open {team.name}</span>
								</Link>
								<Card
									size="sm"
									className="pointer-events-none relative z-20 h-full gap-0 rounded-2xl bg-card py-0 shadow-2xs ring-1 ring-border transition-all duration-200 group-hover:-translate-y-1 group-hover:border-brand_teal-500/40 group-hover:shadow-md dark:group-hover:ring-brand_teal-500/30"
								>
									<CardHeader className="gap-3 px-4 pt-4 pb-3">
										<div className="flex items-center justify-between gap-3">
											<div className="flex min-w-0 items-center gap-2.5">
												<Avatar size="sm">
													<AvatarFallback className="bg-brand_navy-500/10 text-brand_navy-700 dark:bg-brand_mint-500/15 dark:text-brand_mint-300 text-[10px] font-semibold">
														{teamInitials(team.name)}
													</AvatarFallback>
												</Avatar>
												<CardTitle className="line-clamp-1 text-sm font-semibold tracking-tight transition-colors group-hover:text-brand_teal-600 dark:group-hover:text-brand_mint-400">
													{team.name}
												</CardTitle>
											</div>
											<Badge
												variant="secondary"
												className="h-5 px-2 text-[10px] font-medium border-border/50"
											>
												{team.accessRole === "owner"
													? "Owner"
													: team.accessRole === "manager"
														? "Manager"
														: "Member"}
											</Badge>
										</div>
									</CardHeader>
									<CardContent className="px-4 pb-4">
										<div className="flex items-center justify-between text-xs text-muted-foreground">
											<span className="inline-flex items-center gap-1.5 font-medium">
												<UsersRound
													className="size-3.5 text-brand_teal-600 dark:text-brand_mint-400"
													aria-hidden="true"
												/>
												{team.memberCount}{" "}
												{team.memberCount === 1 ? "member" : "members"}
											</span>
											<span className="text-[11px]">Active team</span>
										</div>
									</CardContent>
								</Card>
							</div>
						))}
					</div>
				) : (
					<Empty className="h-full min-h-80 border-0">
						<EmptyHeader>
							<EmptyMedia variant="icon">
								<UsersRound />
							</EmptyMedia>
							<EmptyTitle>
								{search ? "No matching teams" : "No teams yet"}
							</EmptyTitle>
							<EmptyDescription>
								{search
									? "Try a different search term or clear the search."
									: "A team appears when a project gains a second member."}
							</EmptyDescription>
						</EmptyHeader>
					</Empty>
				)}
			</div>

			<footer className="flex items-center justify-between gap-4 border-t pt-3">
				<p className="text-xs text-muted-foreground">
					{visibleTeams.length} {visibleTeams.length === 1 ? "Team" : "Teams"}
				</p>
			</footer>
		</section>
	);
}
